### ISSUE TITLE
Unable to convert deepspeech-0.6.1 model

### ISSUE THREAD

**Issue by smitesh-sutaria** [FengYen-Chang/DeepSpeechOpenVINO#1]
Using https://github.com/FengYen-Chang/open_model_zoo/tree/master/demos/python_demos/deep_speech_demo able to convert deepspeech-0.5.1 model.

But when attempt it on 0.6.1 version, get the below error :

```

python3 ./mo_tf.py --input_model /root/deepspeech-0.6.0-models/output_graph.pb --freeze_placeholder_with_value "input_lengths->[16]" --input input_node,previous_state_h/read,previous_state_c/read --input_shape [1,16,19,26],[1,2048],[1,2048] --output Softmax,lstm_fused_cell/GatherNd,lstm_fused_cell/GatherNd_1 --disable_nhwc_to_nchw
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      /root/deepspeech-0.6.0-models/output_graph.pb
        - Path for generated IR:        /opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/.
        - IR output name:       output_graph
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         input_node,previous_state_h/read,previous_state_c/read
        - Output layers:        Softmax,lstm_fused_cell/GatherNd,lstm_fused_cell/GatherNd_1
        - Input shapes:         [1,16,19,26],[1,2048],[1,2048]
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       False
        - Reverse input channels:       False
TensorFlow specific parameters:
        - Input model in text protobuf format:  False
        - Path to model dump for TensorBoard:   None
        - List of shared libraries with TensorFlow custom layers implementation:        None
        - Update the configuration file with input/output node names:   None
        - Use configuration file used to generate the model with Object Detection API:  None
        - Use the config file:  None
Model Optimizer version:
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.front.user_data_repack.UserDataRepack'>): No node with name previous_state_h/read.
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #51.


```

**Comment by smitesh-sutaria** [comment]
@FengYen-Chang : Any suggestions ?

**Comment by FengYen-Chang** [comment]
Hi @smitesh-sutaria ,

Sorry for the late reply. As this demo is only for 0.5.0 version, the deep speech model might have some difference between `0.5.1` and `0.6.0`. Therefore, the command for model optimizer and the script for demo might not suitable for the `0.6.0` release. 
To acquire the **correct** command for MO, I recommend to use [Netron](https://github.com/lutzroeder/netron) to check the graph, and then acquire the correct node for release `0.6.0`. 

Such as the following figure, you could see input nodes when you select the node `input_node`.
![image](https://user-images.githubusercontent.com/23442770/88411121-f80f4800-ce09-11ea-8aed-912c6f431d88.png)

And you also can use Netron to acquire the correct nodes for output, such as below is the output node of the hidden state `c`.
![image](https://user-images.githubusercontent.com/23442770/88411323-4d4b5980-ce0a-11ea-8a8b-00dc57c8e30d.png)

Really sorry for the late reply.

**Comment by FengYen-Chang** [comment]
Hi @smitesh-sutaria , I have update the demo code to version, `0.6.1`. Thanks.

**Comment by smitesh-sutaria** [comment]
Hi @FengYen-Chang , Thank you so much.

How about the latest version 0.7.4 ? https://github.com/mozilla/DeepSpeech/releases/tag/v0.7.4 
The 0.7.4 does not have .pb model but only the .pbmm.

We were actually interested in using the latest version 0.7.4.

**Comment by FengYen-Chang** [comment]
Hi @smitesh-sutaria ,

Actually, I have not tried the version `0.7.4` yet.
But you can download the `.pb` file from [here](https://github.com/mozilla/DeepSpeech/releases/download/v0.7.4/deepspeech-0.7.4-models.pb) and have a try.

Thanks,
John

**Comment by FengYen-Chang** [comment]
Hi @smitesh-sutaria ,

I have tried the the `.pb` file of `0.7.4` version, the MO command is same, you just need to change the file name of `.pb` model.
For demo, it only need to patch the parameter `upper_frequency_limit` from `4000` to `8000` is this `0.7.4` version, and this patch is commited.

Thanks,
John
